import { logger } from "../../logger";
import { settingsManager } from "../../core/services/settings-manager";
import { providerRegistry, modelRegistry, parseModelRef } from "../../ai/registry";
import { modelConfig } from "../../config/env";
import type { AIMessage } from "../../types";
import type { AIProvider, ProviderId } from "../../ai/types";
import type { ExtractionResult, LtmEntry } from "../core/types";
import { getLtmStore } from "../core/runtime";
import { serializeEmbedding } from "../utils/vector";
import { evictIfOverCap } from "./evictor";

const EXTRACTION_TIMEOUT_MS = 8000;

const EXTRACTION_SYSTEM_PROMPT = `You are a conservative long-term memory maintenance system.
Your job is to decide whether a conversation turn contains information worth persisting about the USER.

You will receive:
1. The current memories already stored (CURRENT MEMORIES).
2. A single conversation turn (user message + assistant response).

You must compare the conversation against CURRENT MEMORIES before deciding what to do.

## WHAT TO EXTRACT 

Only extract information that is ALL of the following:
- About the USER (not the assistant, not third parties)
- Stable and long-lasting (true across sessions, not just today)
- Related to: identity, preferences, habits, goals, persistent traits, long-term projects, communication style, tooling environment, or workflow

Fact examples worth storing:
- {"key":"preferred_language","value":"Prefers TypeScript over JavaScript"}
- {"key":"name","value":"Name: Andi"}
- {"key":"editor","value":"Uses Neovim as primary editor"}

Pattern examples worth storing:
- {"key":"linux_admin","value":"Frequently works on Linux server administration"}
- {"key":"commit_style","value":"Writes concise commit messages"}

## WHAT TO REJECT (mandatory rejections)

You MUST NOT extract any of the following:
- Coding assistance requests or code the assistant wrote
- Debugging sessions or error traces
- Translation requests or translated content
- Summarization requests or summaries produced
- Factual Q&A or general knowledge answers
- Temporary planning, to-do lists, or short-lived tasks
- One-off questions with no lasting relevance
- Content generated by the assistant (the assistant's knowledge, actions, or output)
- Information that is already captured in CURRENT MEMORIES with the same meaning
- Information that merely rephrases an existing memory without adding new substance

Negative examples; do NOT store these:
- User asks a coding/debugging question -> nothing
- User asks for translation/summary -> nothing  
- User asks factual Q&A -> nothing
- User makes a one-off request -> nothing
- Assistant explains something -> nothing

## DUPLICATE PREVENTION

Before extracting, compare each candidate memory against CURRENT MEMORIES:
- If a fact with the same key already exists and the value is the same or equivalent -> skip it
- If a fact with the same key exists but the value has meaningfully changed -> output it as an update (same key, new value)
- If a pattern already covers the same behavior -> skip it
- Never create a new fact or pattern that duplicates the meaning of an existing one

## VALUE STYLE (mandatory)

Values MUST be atomic and concise. Drop the subject ("The user", "I", "He/She").
Write values like short notes, not full sentences.

GOOD values:
- "Prefers TypeScript over JavaScript"
- "Name: Andi"
- "Uses Neovim as primary editor"
- "Works on Linux server administration"
- "Writes concise commit messages"
- "On 1 June, has a date with Natalie"

BAD values (too verbose or wrong style):
- "The user prefers TypeScript over JavaScript."
- "I use Neovim as their primary editor."
- "The user frequently works on Linux server administration tasks."

## OUTPUT FORMAT

Return strict JSON only:
{"facts":[{"key":"snake_case_key","value":"Prefers X over Y"}],"patterns":[{"key":"snake_case_key","value":"Frequently does X"}],"episodic":[{"value":"On 1 June, configured X for Y"}]}

Rules:
- Use canonical English snake_case keys for facts and patterns.
- Keep values in the original language when appropriate.
- Values must be atomic - one fact per entry, no compound statements.
- Episodic memories should only capture genuinely notable interactions, not routine exchanges.
- When in doubt, do NOT extract. Returning empty arrays is the correct and preferred outcome for most turns.

If nothing is worth storing, return:
{"facts":[],"patterns":[],"episodic":[]}`;

export function resolveExtractionProvider(): { provider: AIProvider; model: string } | null {
  const settings = settingsManager.get();
  const configuredProvider = settings.ltm.provider.trim();
  const configuredModel = settings.ltm.model.trim();

  if (configuredProvider && configuredModel) {
    try {
      return {
        provider: providerRegistry.require(configuredProvider as ProviderId),
        model: configuredModel,
      };
    } catch (error) {
      logger.debug("ltm:extract", `Configured extraction provider unavailable: ${String(error)}`);
    }
  }

  try {
    const [resolved] = modelRegistry.resolveModels(modelConfig.primaryModel, []);
    if (!resolved) {
      logger.debug("ltm:extract", "No main provider available for LTM extraction fallback");
      return null;
    }
    return {
      provider: providerRegistry.require(resolved.providerId as ProviderId),
      model: resolved.modelId,
    };
  } catch (error) {
    logger.debug("ltm:extract", `Extraction provider fallback failed: ${String(error)}`);
    return null;
  }
}

function providerSupportsEmbeddings(provider: AIProvider): boolean {
  if (typeof provider.embed !== "function") return false;
  try {
    return provider.capabilities().embeddingsSupported === true;
  } catch {
    return false;
  }
}

/**
 * Attempts to load a provider+model pair from a provider:model reference
 * or a bare model id (combined with the supplied fallback provider id)
 * Returns null when the provider is not registered or does not expose
 * embeddings
 */
function tryLoadEmbeddingTarget(
  ref: string,
  fallbackProviderId: string | undefined,
  source: string
): { provider: AIProvider; model: string } | null {
  const trimmed = ref.trim();
  if (!trimmed) return null;

  let providerId: string;
  let modelId: string;
  if (trimmed.includes(":")) {
    try {
      const parsed = parseModelRef(trimmed);
      providerId = parsed.providerId;
      modelId = parsed.modelId;
    } catch (error) {
      logger.debug("ltm:embedding", `Invalid embedModel reference (${source}): ${String(error)}`);
      return null;
    }
  } else {
    if (!fallbackProviderId) {
      logger.debug("ltm:embedding", `embedModel '${trimmed}' (${source}) has no provider prefix and no default provider is configured`);
      return null;
    }
    providerId = fallbackProviderId.toLowerCase();
    modelId = trimmed;
  }

  let provider: AIProvider;
  try {
    provider = providerRegistry.require(providerId as ProviderId);
  } catch (error) {
    logger.debug("ltm:embedding", `embedModel provider unavailable (${source}): ${String(error)}`);
    return null;
  }

  if (!providerSupportsEmbeddings(provider)) {
    logger.debug(
      "ltm:embedding",
      `embedModel provider '${providerId}' (${source}) does not support embeddings; skipping`
    );
    return null;
  }

  return { provider, model: modelId };
}

/**
 * Resolves the active embedding provider/model pair
 * Priority:
 *   1. settings.ltm.embedModel (explicit user override; may be a bare model id
 *      combined with `settings.ltm.provider`, or a full `provider:model` ref)
 *
 *   2.`DESKLUMINA_EMBED_MODEL` env var / `models.json` `primary.embedModel`
 *      (surfaced through `modelConfig.primaryEmbedModel`)
 *
 *   3.Safe fallback: `ltm.provider` + `ltm.model` when that provider supports
 *      embeddings (preserves pre-`embedModel` behavior)
 *
 *   4. Walk the main chat model + fallback chain for any registered provider
 *      that exposes embeddings.
 *   5. `null` (with diagnostic logging).
 */
export function resolveEmbeddingProvider(): { provider: AIProvider; model: string } | null {
  const settings = settingsManager.get();
  const configuredProvider = settings.ltm.provider.trim();
  const configuredEmbedModel = (settings.ltm.embedModel ?? "").trim();

  if (configuredEmbedModel) {
    const resolved = tryLoadEmbeddingTarget(
      configuredEmbedModel,
      configuredProvider || undefined,
      "settings.ltm.embedModel"
    );
    if (resolved) return resolved;
  }

  const envEmbedModel = (modelConfig.primaryEmbedModel ?? "").trim();
  if (envEmbedModel) {
    const resolved = tryLoadEmbeddingTarget(envEmbedModel, undefined, "DESKLUMINA_EMBED_MODEL/models.json");
    if (resolved) return resolved;
  }

  //safe fallback, reuse the LTM chat model only when that provider
  // actually supports embeddings. This preserves the historical behavior for
  // configurations that intentionally point ltm.model at an embedding model.
  const extraction = resolveExtractionProvider();
  if (extraction && providerSupportsEmbeddings(extraction.provider)) {
    return extraction;
  }

  try {
    const candidates = modelRegistry.resolveModels(
      modelConfig.primaryModel,
      modelConfig.fallbackModels
    );
    for (const candidate of candidates) {
      let provider: AIProvider;
      try {
        provider = providerRegistry.require(candidate.providerId as ProviderId);
      } catch {
        continue;
      }
      if (providerSupportsEmbeddings(provider)) {
        return { provider, model: candidate.modelId };
      }
    }
  } catch (error) {
    logger.debug("ltm:embedding", `Embedding provider chain walk failed: ${String(error)}`);
  }

  if (extraction) {
    logger.debug(
      "ltm:embedding",
      `Embedding unsupported by provider=${extraction.provider.id}, model=${extraction.model}; configure ltm.embedModel or DESKLUMINA_EMBED_MODEL`
    );
  } else {
    logger.debug(
      "ltm:embedding",
      "No embedding-capable provider available; configure ltm.embedModel or DESKLUMINA_EMBED_MODEL"
    );
  }
  return null;
}

export async function generateEmbedding(
  text: string,
  timeoutMs = EXTRACTION_TIMEOUT_MS
): Promise<number[] | null> {
  const resolved = resolveEmbeddingProvider();
  if (!resolved) return null;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await resolved.provider.embed?.({
      input: text,
      model: resolved.model,
      signal: controller.signal,
    });

    if (!response || !Array.isArray(response.embedding)) {
      logger.debug("ltm:embedding", "ltm:vector invalid (missing embedding array)");
      return null;
    }

    logger.debug("ltm:embedding", `ltm:embedding generated provider=${resolved.provider.id} model=${resolved.model}`);
    return response.embedding;
  } catch (error) {
    logger.debug("ltm:embedding", `ltm:embedding failed provider=${resolved.provider.id} model=${resolved.model}: ${String(error)}`);
    return null;
  } finally {
    clearTimeout(timer);
  }
}

function formatMemoryContext(facts: LtmEntry[], patterns: LtmEntry[]): string {
  if (facts.length === 0 && patterns.length === 0) {
    return "CURRENT MEMORIES: (empty; none)";
  }

  const lines: string[] = ["CURRENT MEMORIES:"];

  if (facts.length > 0) {
    lines.push("Facts:");
    for (const f of facts) {
      lines.push(`- [${f.key}]: ${f.value}`);
    }
  }

  if (patterns.length > 0) {
    lines.push("Patterns:");
    for (const p of patterns) {
      lines.push(`- [${p.key}]: ${p.value}`);
    }
  }

  return lines.join("\n");
}

export async function callExtractionLLM(
  provider: AIProvider,
  model: string,
  messages: AIMessage[],
  timeoutMs = EXTRACTION_TIMEOUT_MS
): Promise<string> {
  const controller = new AbortController();
  const consume = async () => {
    let response = "";
    for await (const chunk of provider.streamChat({
      messages,
      model,
      temperature: 0.3,
      maxTokens: 800,
      signal: controller.signal,
    })) {
      if (chunk.content) response += chunk.content;
    }
    return response;
  };

  const consumePromise = consume();
  consumePromise.catch(() => {});

  let timeout: ReturnType<typeof setTimeout> | null = null;
  const timeoutPromise = new Promise<string>((_, reject) => {
    timeout = setTimeout(() => {
      controller.abort();
      reject(new Error("LTM extraction timed out"));
    }, timeoutMs);
  });

  try {
    return await Promise.race([consumePromise, timeoutPromise]);
  } finally {
    if (timeout) clearTimeout(timeout);
  }
}

export function parseExtractionResult(raw: string): ExtractionResult | null {
  const candidates = [raw.trim()];
  const fenceMatch = raw.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenceMatch?.[1]) {
    candidates.unshift(fenceMatch[1].trim());
  }

  for (const candidate of candidates) {
    try {
      const parsed = JSON.parse(candidate) as Partial<ExtractionResult>;
      if (!Array.isArray(parsed.facts) || !Array.isArray(parsed.patterns) || !Array.isArray(parsed.episodic)) {
        continue;
      }

      return {
        facts: parsed.facts
          .filter((entry): entry is { key: string; value: string } =>
            Boolean(entry)
            && typeof entry.key === "string"
            && entry.key.trim().length > 0
            && typeof entry.value === "string"
            && entry.value.trim().length > 0
          )
          .map((entry) => ({ key: entry.key.trim(), value: entry.value.trim() })),
        patterns: parsed.patterns
          .filter((entry): entry is { key: string; value: string } =>
            Boolean(entry)
            && typeof entry.key === "string"
            && entry.key.trim().length > 0
            && typeof entry.value === "string"
            && entry.value.trim().length > 0
          )
          .map((entry) => ({ key: entry.key.trim(), value: entry.value.trim() })),
        episodic: parsed.episodic
          .filter((entry): entry is { value: string } =>
            Boolean(entry)
            && typeof entry.value === "string"
            && entry.value.trim().length > 0
          )
          .map((entry) => ({ value: entry.value.trim() })),
      };
    } catch {
      //try the next candidate
    }
  }

  return null;
}

export async function extractMemories(
  userMessage: string,
  assistantResponse: string
): Promise<void> {
  if (!settingsManager.get().features.ltm) return;

  try {
    const resolved = resolveExtractionProvider();
    const store = getLtmStore();
    if (!resolved || !store) return;

    const existingFacts = store.getAllFacts();
    const existingPatterns = store.getAllPatterns();
    const memoryContext = formatMemoryContext(existingFacts, existingPatterns);
    const responseHint = assistantResponse.slice(0, 60);

    logger.debug("ltm:extract", `Extraction started: provider=${resolved.provider.id}, model=${resolved.model}`);
    const raw = await callExtractionLLM(resolved.provider, resolved.model, [
      { role: "system", content: EXTRACTION_SYSTEM_PROMPT },
      {
        role: "user",
        content: `${memoryContext}\n\n---\n\nUser message:\n${userMessage}\n\nContext:\n${responseHint}...`,
      },
    ]);
    const parsed = parseExtractionResult(raw);
    if (!parsed) {
      logger.debug("ltm:extract", `Extraction failed: invalid JSON response: ${raw.slice(0, 500)}`);
      return;
    }

    if (parsed.facts.length === 0 && parsed.patterns.length === 0 && parsed.episodic.length === 0) {
      logger.debug("ltm:extract", "Extraction completed: nothing worth storing (empty result)");
      return;
    }

    let factsWritten = 0;
    let patternsWritten = 0;
    let episodicWritten = 0;

    for (const fact of parsed.facts) {
      const existing = store.getByKey("fact", fact.key);
      if (existing && existing.value === fact.value) continue;
      store.upsertFact(fact.key, fact.value);
      factsWritten++;
    }

    for (const pattern of parsed.patterns) {
      const existing = store.getByKey("pattern", pattern.key);
      if (existing && existing.value === pattern.value) continue;
      store.upsertPattern(pattern.key, pattern.value);
      patternsWritten++;
    }

    for (const entry of parsed.episodic) {
      if (store.hasEpisodicValue(entry.value)) continue;

      const embedding = await generateEmbedding(entry.value);
      const embeddingJson = embedding ? serializeEmbedding(embedding) : null;
      if (embedding && !embeddingJson) {
        logger.debug("ltm:embedding", "ltm:vector invalid (non-finite embedding)");
      }

      store.insertEpisodic(entry.value, embeddingJson);
      episodicWritten++;
    }

    if (episodicWritten > 0) {
      evictIfOverCap(store, settingsManager.get().ltm.episodicCap);
    }

    logger.debug(
      "ltm:extract",
      `Extraction completed: facts=${factsWritten}, patterns=${patternsWritten}, episodic=${episodicWritten} (skipped duplicates: facts=${parsed.facts.length - factsWritten}, patterns=${parsed.patterns.length - patternsWritten}, episodic=${parsed.episodic.length - episodicWritten})`
    );
  } catch (error) {
    logger.debug("ltm:extract", `Extraction failed: ${String(error)}`);
  }
}
